# Change these first
owner: helpy4 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Cloudflare
    url: https://cloudflare.com
  - name: Панель panel.helpy4.ru
    url: https://panel.helpy4.ru
    ipv6: true
  - name: Облако cloud.romax-host.ru:4444
    url: cloud.romax-host.ru
    port: 4444
    #check: "tcp-ping"
    ipv6: true
  - name: Управление хостингом
    url: https://pve.helpy4.ru
    #ipv6: true

i18n:
  allSystemsOperational: Все системы работают.

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.romax-host.ru
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Статус Хостинга helpy4"
  introTitle: "**Привет!** Эта страница ещё не готова."
  introMessage: русский This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
